version: '3.5.{build}'
image: 
- Visual Studio 2017
- Ubuntu
platform: Any CPU
stack: node 9
notifications:
- provider: Slack
  auth_token:
    secure: Q+xg4/yU5OR9BVF14cw4yZ+3qlhMeYDsAhUQyOIszmF1mHvq44tIvQpWByBJCd/cgUIZk3SwBpk4hh1MrkQIk6rnaOZ2LNBTev4zrq36oXk=
  channel: '#builds'
install:
- ps: |
        if($isWindows)
        {
            Install-Product node 8
        }
before_build:
- dotnet restore --verbosity q
- cmd: iisreset
- cmd: net start W3SVC
build_script:
- cmd: dotnet publish --configuration Release --runtime win-x64 --output "C:/passcore"
- sh: dotnet publish --configuration Release --runtime linux-x64 /p:PASSCORE_PROVIDER=LDAP
- ps: |
        if($isWindows)
        {
            ./IISSetup.ps1 "C:/passcore"
        }
