version: '3.0.{build}'
image: Visual Studio 2017
platform: Any CPU
install:
- ps: Install-Product node 8
before_build:
- dotnet restore --verbosity q
- iisreset
- net start W3SVC
build_script:
- dotnet publish -c Release --output "C:/passcore"
- ps: ./IISWebsite.ps1 "C:/passcore"
